version: '3'

services:
  appschedule:
    image: appschedule-campus
    depends_on:
      - apischedule
    ports:
      - "4200"

  apischedule:
    image: apischedule-campus
    build:
      context: ./api
    ports:
      - "5001"

  databaseschedule:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434"
